import type { Metadata } from 'next';
import { Inter as FontSans, Geist_Mono as FontMono } from 'next/font/google';
import './globals.css';

const fontSans = FontSans({
  variable: '--font-font-sans',
  subsets: ['latin'],
});

const fontMono = FontMono({
  variable: '--font-font-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fontSans.variable} ${fontMono.variable}`}
      suppressHydrationWarning
    >
      <body className="antialiased min-h-screen flex flex-col">
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
