import type { Metadata } from 'next';
import { Inter as FontSans, Geist_Mono as FontMono } from 'next/font/google';
import './globals.css';
import AppWrapper from '@/components/AppWrapper';
import { SessionProvider } from 'next-auth/react';
import { Toaster } from '@/components/ui/sonner';

const fontSans = FontSans({
  variable: '--font-font-sans',
  subsets: ['latin'],
});

const fontMono = FontMono({
  variable: '--font-font-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fontSans.variable} ${fontMono.variable}`}
      suppressHydrationWarning
    >
      <body className="antialiased min-h-screen flex flex-col">
        <SessionProvider>
          <AppWrapper>
            <main className="flex-1">{children}</main>
            <Toaster
              toastOptions={{
                className: 'my-custom-toast',
              }}
            />
          </AppWrapper>
        </SessionProvider>
      </body>
    </html>
  );
}
